"""ORM model for the ``dim_users`` user dimension table."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class DimUser(Base):
    """User dimension: one row per distinct Claude Code user identity.

    Surrogate key ``user_sk`` is generated by the database. Natural key ``user_id``
    is the Claude Code install or IdP subject identifier used for idempotent upserts.
    """

    __tablename__ = "dim_users"

    user_sk: Mapped[int] = mapped_column(
        BigInteger,
        Identity(),
        primary_key=True,
    )
    user_id: Mapped[str] = mapped_column(String, unique=True, index=True)
    account_uuid: Mapped[str | None] = mapped_column(String, nullable=True)
    email: Mapped[str | None] = mapped_column(String, nullable=True)
    practice: Mapped[str | None] = mapped_column(String, nullable=True)
    level: Mapped[str | None] = mapped_column(String, nullable=True)
    location: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        """Return a debug-friendly representation of the user row."""
        return f"<DimUser(user_sk={self.user_sk!r}, user_id={self.user_id!r})>"
