"""create dim_users table

Revision ID: a3743cb8a35d
Revises: 
Create Date: 2026-07-23 11:02:39.427958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3743cb8a35d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_users',
    sa.Column('user_sk', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_uuid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('practice', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_sk')
    )
    op.create_index(op.f('ix_dim_users_user_id'), 'dim_users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_users_user_id'), table_name='dim_users')
    op.drop_table('dim_users')
    # ### end Alembic commands ###
