"""create fact_api_requests table

Revision ID: f5875ee56345
Revises: a3743cb8a35d
Create Date: 2026-07-23 17:06:33.312996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5875ee56345'
down_revision: Union[str, Sequence[str], None] = 'a3743cb8a35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_api_requests',
    sa.Column('request_sk', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_sk')
    )
    op.create_index(op.f('ix_fact_api_requests_event_ts'), 'fact_api_requests', ['event_ts'], unique=False)
    op.create_index(op.f('ix_fact_api_requests_model_name'), 'fact_api_requests', ['model_name'], unique=False)
    op.create_index(op.f('ix_fact_api_requests_user_email'), 'fact_api_requests', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_api_requests_user_email'), table_name='fact_api_requests')
    op.drop_index(op.f('ix_fact_api_requests_model_name'), table_name='fact_api_requests')
    op.drop_index(op.f('ix_fact_api_requests_event_ts'), table_name='fact_api_requests')
    op.drop_table('fact_api_requests')
    # ### end Alembic commands ###
